"""init

Revision ID: 001
Revises: 
Create Date: 2026-01-26 18:16:09.594958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features'))
    )
    op.create_index(op.f('ix_features_code'), 'features', ['code'], unique=True)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('plans',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('plan_limits',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('feature_limit', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_plan_limits_feature_id_features'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_limits_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_limits')),
    sa.UniqueConstraint('plan_id', 'feature_id', name='uq_plan_feature_limit')
    )
    op.create_index(op.f('ix_plan_limits_feature_id'), 'plan_limits', ['feature_id'], unique=False)
    op.create_index(op.f('ix_plan_limits_plan_id'), 'plan_limits', ['plan_id'], unique=False)
    op.create_table('plan_permissions',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_plan_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_permissions_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_permissions')),
    sa.UniqueConstraint('plan_id', 'permission_id', name='uq_plan_permission')
    )
    op.create_index(op.f('ix_plan_permissions_permission_id'), 'plan_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_plan_permissions_plan_id'), 'plan_permissions', ['plan_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_tokens_cleanup', 'refresh_tokens', ['expires_at', 'revoked_at'], unique=False)
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_hash_active', 'refresh_tokens', ['token_hash'], unique=False, postgresql_where='revoked_at IS NULL')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_plans',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=False),
    sa.Column('custom_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_user_plans_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_plans'))
    )
    op.create_index('ix_user_plans_active_lookup', 'user_plans', ['user_id', 'started_at', 'ends_at'], unique=False)
    op.create_index('ix_user_plans_active_not_cancelled', 'user_plans', ['user_id', 'started_at', 'ends_at'], unique=False, postgresql_where='is_cancelled = false')
    op.create_index(op.f('ix_user_plans_plan_id'), 'user_plans', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_plans_user_id'), 'user_plans', ['user_id'], unique=False)
    op.create_table('user_providers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('external_user_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_providers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_providers'))
    )
    op.create_index(op.f('ix_user_providers_external_user_id'), 'user_providers', ['external_user_id'], unique=False)
    op.create_index('ix_user_providers_unique', 'user_providers', ['code', 'external_user_id'], unique=True)
    op.create_index(op.f('ix_user_providers_user_id'), 'user_providers', ['user_id'], unique=False)
    op.create_table('feature_usage',
    sa.Column('user_plan_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('feature_usage', sa.BigInteger(), nullable=False),
    sa.Column('start_period', sa.Date(), nullable=False),
    sa.Column('end_period', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_feature_usage_feature_id_features'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_plan_id'], ['user_plans.id'], name=op.f('fk_feature_usage_user_plan_id_user_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_usage')),
    sa.UniqueConstraint('user_plan_id', 'feature_id', 'start_period', name='uq_usage_plan_feature_period')
    )
    op.create_index(op.f('ix_feature_usage_feature_id'), 'feature_usage', ['feature_id'], unique=False)
    op.create_index('ix_feature_usage_period_lookup', 'feature_usage', ['user_plan_id', 'feature_id', 'start_period', 'end_period'], unique=False)
    op.create_index(op.f('ix_feature_usage_user_plan_id'), 'feature_usage', ['user_plan_id'], unique=False)
    # ### end Alembic commands ###

    # Seed default role and plan
    op.execute("""
        INSERT INTO roles (id, code, name) VALUES
        (gen_random_uuid(), 'user', 'User');
    """)
    op.execute("""
        INSERT INTO plans (id, code, name) VALUES
        (gen_random_uuid(), 'free', 'Free');
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_usage_user_plan_id'), table_name='feature_usage')
    op.drop_index('ix_feature_usage_period_lookup', table_name='feature_usage')
    op.drop_index(op.f('ix_feature_usage_feature_id'), table_name='feature_usage')
    op.drop_table('feature_usage')
    op.drop_index(op.f('ix_user_providers_user_id'), table_name='user_providers')
    op.drop_index('ix_user_providers_unique', table_name='user_providers')
    op.drop_index(op.f('ix_user_providers_external_user_id'), table_name='user_providers')
    op.drop_table('user_providers')
    op.drop_index(op.f('ix_user_plans_user_id'), table_name='user_plans')
    op.drop_index(op.f('ix_user_plans_plan_id'), table_name='user_plans')
    op.drop_index('ix_user_plans_active_not_cancelled', table_name='user_plans', postgresql_where='is_cancelled = false')
    op.drop_index('ix_user_plans_active_lookup', table_name='user_plans')
    op.drop_table('user_plans')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_hash_active', table_name='refresh_tokens', postgresql_where='revoked_at IS NULL')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_cleanup', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_plan_permissions_plan_id'), table_name='plan_permissions')
    op.drop_index(op.f('ix_plan_permissions_permission_id'), table_name='plan_permissions')
    op.drop_table('plan_permissions')
    op.drop_index(op.f('ix_plan_limits_plan_id'), table_name='plan_limits')
    op.drop_index(op.f('ix_plan_limits_feature_id'), table_name='plan_limits')
    op.drop_table('plan_limits')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_features_code'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
